// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // Prisma 7: seed must live here (package.json prisma.seed is ignored).
    // On Render prefer Start without `db seed` — staff bootstrap runs in instrumentation.
    seed: "node ./scripts/ensure-staff.mjs",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
