import type { FaqCategory } from "./faq.categories";
import { FEATURED_FAQ_SLUGS } from "./faq.categories";

export type FaqSeed = {
  slug: string;
  category: FaqCategory;
  displayOrder: number;
  isFeatured?: boolean;
  questionAr: string;
  questionEn: string;
  questionFr: string;
  answerAr: string;
  answerEn: string;
  answerFr: string;
  keywordsAr: string[];
  keywordsEn: string[];
  keywordsFr: string[];
  relatedSpecialtySlugs?: string[];
  relatedServiceSlugs?: string[];
};

export const FAQ_SEEDS: FaqSeed[] = [
  {
    displayOrder: 1,
    slug: "clinic-services",
    category: "general",
    questionAr: "ما الخدمات التي تقدمها عيادة الوسام؟",
    questionEn: "What services does Al Wissam Dental Clinic offer?",
    questionFr: "Quels services propose la Clinique Dentaire El Wissam ?",
    answerAr: "تقدم عيادة الوسام خدمات متنوعة في طب الأسنان، تشمل الفحص والتشخيص، تنظيف الأسنان واللثة، الحشوات، علاج العصب والجذور، خلع الأسنان، تقويم الأسنان، تبييض الأسنان، التركيبات والتيجان والجسور، زراعة الأسنان، وطب أسنان الأطفال. تظهر الخدمات المتاحة فعليًا داخل الموقع ويمكن اختيارها عند الحجز.",
    answerEn: "Al Wissam Dental Clinic offers a range of dental services including examination and diagnosis, teeth and gum cleaning, fillings, root canal treatment, extractions, orthodontics, whitening, crowns and bridges, dental implants, and pediatric dentistry. Available services are listed on the website and can be selected when booking.",
    answerFr: "La Clinique Dentaire El Wissam propose divers soins dentaires : examen et diagnostic, nettoyage des dents et des gencives, obturations, traitement de canal, extractions, orthodontie, blanchiment, couronnes et bridges, implants et dentisterie pédiatrique. Les services disponibles apparaissent sur le site et peuvent être choisis lors de la réservation.",
    keywordsAr: ["خدمات", "عيادة", "طب أسنان"],
    keywordsEn: ["services", "clinic", "dentistry"],
    keywordsFr: ["services", "clinique", "dentaire"],
  },
  {
    displayOrder: 2,
    slug: "clinic-location",
    category: "contact-location",
    isFeatured: true,
    questionAr: "أين تقع عيادة الوسام؟",
    questionEn: "Where is Al Wissam Dental Clinic located?",
    questionFr: "Où se situe la Clinique Dentaire El Wissam ?",
    answerAr: "تقع عيادة الوسام في حي الأمير عبد القادر، بجانب ابتدائية زكور فرحات الصغير، الوادي، الجزائر 39009. يمكنك فتح اتجاهات الوصول مباشرة من صفحة التواصل عبر خرائط Google.",
    answerEn: "Al Wissam Dental Clinic is located in El Amir Abdelkader neighborhood, next to Zakour Farhat El Saghir primary school, El Oued, Algeria 39009. You can open directions from the contact page via Google Maps.",
    answerFr: "La Clinique Dentaire El Wissam se situe dans le quartier El Amir Abdelkader, à côté de l’école primaire Zakour Farhat El Saghir, El Oued, Algérie 39009. Vous pouvez ouvrir l’itinéraire depuis la page Contact via Google Maps.",
    keywordsAr: ["موقع", "عنوان", "الوادي"],
    keywordsEn: ["location", "address", "El Oued"],
    keywordsFr: ["localisation", "adresse", "El Oued"],
  },
  {
    displayOrder: 3,
    slug: "clinic-contact",
    category: "contact-location",
    questionAr: "كيف يمكنني التواصل مع العيادة؟",
    questionEn: "How can I contact the clinic?",
    questionFr: "Comment puis-je contacter la clinique ?",
    answerAr: "يمكنك الاتصال بالعيادة على الرقم 0663 09 82 08، أو التواصل عبر واتساب، أو إرسال استفسار من صفحة التواصل، أو مراسلتنا عبر البريد الإلكتروني clinic.elwissam@gmail.com.",
    answerEn: "You can call the clinic at 0663 09 82 08, reach us on WhatsApp, send an inquiry from the contact page, or email clinic.elwissam@gmail.com.",
    answerFr: "Vous pouvez appeler la clinique au 0663 09 82 08, nous joindre sur WhatsApp, envoyer une demande depuis la page Contact, ou écrire à clinic.elwissam@gmail.com.",
    keywordsAr: ["تواصل", "هاتف", "واتساب"],
    keywordsEn: ["contact", "phone", "WhatsApp"],
    keywordsFr: ["contact", "téléphone", "WhatsApp"],
  },
  {
    displayOrder: 4,
    slug: "walk-in-without-appointment",
    category: "appointments",
    questionAr: "هل يمكنني زيارة العيادة دون موعد؟",
    questionEn: "Can I visit the clinic without an appointment?",
    questionFr: "Puis-je venir sans rendez-vous ?",
    answerAr: "يمكنك التواصل مع العيادة للاستفسار عن إمكانية الاستقبال دون موعد، لكن الحجز المسبق يساعد على اختيار الطبيب والوقت المناسب وتقليل الانتظار.",
    answerEn: "You can contact the clinic to ask about walk-in availability, but booking ahead helps choose a suitable doctor and time and usually reduces waiting.",
    answerFr: "Vous pouvez contacter la clinique pour savoir si un accueil sans rendez-vous est possible, mais réserver à l’avance aide à choisir le médecin et l’horaire et réduit souvent l’attente.",
    keywordsAr: ["بدون موعد", "زيارة"],
    keywordsEn: ["walk-in", "appointment"],
    keywordsFr: ["sans rendez-vous", "visite"],
  },
  {
    displayOrder: 5,
    slug: "parking-near-clinic",
    category: "contact-location",
    questionAr: "هل توجد مواقف سيارات بالقرب من العيادة؟",
    questionEn: "Is there parking near the clinic?",
    questionFr: "Y a-t-il un parking près de la clinique ?",
    answerAr: "يرجى التواصل مع فريق العيادة قبل الحضور للحصول على أحدث المعلومات المتعلقة بمواقف السيارات والوصول إلى الموقع.",
    answerEn: "Please contact the clinic team before your visit for the latest information about parking and how to reach the location.",
    answerFr: "Veuillez contacter l’équipe avant votre visite pour les informations à jour sur le stationnement et l’accès au site.",
    keywordsAr: ["موقف", "سيارات"],
    keywordsEn: ["parking", "cars"],
    keywordsFr: ["parking", "voitures"],
  },
  {
    displayOrder: 6,
    slug: "clinic-working-hours",
    category: "working-hours",
    isFeatured: true,
    questionAr: "ما ساعات عمل العيادة؟",
    questionEn: "What are the clinic’s working hours?",
    questionFr: "Quels sont les horaires de la clinique ?",
    answerAr: "تعمل العيادة من السبت إلى الخميس، من الساعة 08:00 إلى الساعة 17:00. يوم الجمعة مغلق، ما لم يتم الإعلان عن استثناء رسمي.",
    answerEn: "The clinic is open Saturday to Thursday, from 08:00 to 17:00. Friday is closed unless an official exception is announced.",
    answerFr: "La clinique est ouverte du samedi au jeudi, de 08:00 à 17:00. Le vendredi est fermé, sauf exception officielle annoncée.",
    keywordsAr: ["ساعات", "عمل", "دوام"],
    keywordsEn: ["hours", "schedule"],
    keywordsFr: ["horaires", "ouverture"],
  },
  {
    displayOrder: 7,
    slug: "friday-closed",
    category: "working-hours",
    questionAr: "هل تعمل العيادة يوم الجمعة؟",
    questionEn: "Is the clinic open on Fridays?",
    questionFr: "La clinique est-elle ouverte le vendredi ?",
    answerAr: "العيادة مغلقة يوم الجمعة حسب جدول العمل الحالي.",
    answerEn: "The clinic is closed on Fridays according to the current schedule.",
    answerFr: "La clinique est fermée le vendredi selon l’horaire actuel.",
    keywordsAr: ["الجمعة", "مغلق"],
    keywordsEn: ["Friday", "closed"],
    keywordsFr: ["vendredi", "fermé"],
  },
  {
    displayOrder: 8,
    slug: "hours-may-change",
    category: "working-hours",
    questionAr: "هل يمكن أن تتغير ساعات العمل؟",
    questionEn: "Can working hours change?",
    questionFr: "Les horaires peuvent-ils changer ?",
    answerAr: "قد تتغير ساعات العمل في العطل أو الظروف الاستثنائية. يعرض الموقع بيانات العيادة المحدثة، ويمكنك التواصل معنا للتأكد قبل الحضور.",
    answerEn: "Hours may change during holidays or exceptional circumstances. The website shows updated clinic details, and you can contact us to confirm before arriving.",
    answerFr: "Les horaires peuvent changer pendant les vacances ou en circonstances exceptionnelles. Le site affiche les informations à jour, et vous pouvez nous contacter pour confirmer avant de venir.",
    keywordsAr: ["تغيير", "عطلة"],
    keywordsEn: ["change", "holiday"],
    keywordsFr: ["changement", "vacances"],
  },
  {
    displayOrder: 9,
    slug: "how-to-book-appointment",
    category: "appointments",
    isFeatured: true,
    questionAr: "كيف يمكنني حجز موعد؟",
    questionEn: "How can I book an appointment?",
    questionFr: "Comment puis-je prendre rendez-vous ?",
    answerAr: "يمكنك حجز موعد من الموقع باختيار التخصص أو الخدمة، ثم الطبيب، ثم التاريخ والوقت المتاح، وإدخال بيانات المريض وإرسال طلب الحجز.",
    answerEn: "You can book on the website by selecting a specialty or service, then a doctor, then an available date and time, entering patient details, and submitting the booking request.",
    answerFr: "Vous pouvez réserver sur le site en choisissant une spécialité ou un service, puis un médecin, puis une date et une heure disponibles, en saisissant les informations du patient et en envoyant la demande.",
    keywordsAr: ["حجز", "موعد"],
    keywordsEn: ["book", "appointment"],
    keywordsFr: ["réserver", "rendez-vous"],
  },
  {
    displayOrder: 10,
    slug: "booking-not-immediately-confirmed",
    category: "appointments",
    questionAr: "هل الحجز عبر الموقع مؤكد مباشرة؟",
    questionEn: "Is an online booking confirmed immediately?",
    questionFr: "La réservation en ligne est-elle confirmée immédiatement ?",
    answerAr: "يتم تسجيل طلب الحجز أولًا، ثم يتواصل فريق العيادة معك لتأكيد الموعد. لا يعتبر الموعد مؤكدًا إلا بعد استلام تأكيد العيادة.",
    answerEn: "The booking request is recorded first, then the clinic team contacts you to confirm. The appointment is confirmed only after you receive clinic confirmation.",
    answerFr: "La demande est d’abord enregistrée, puis l’équipe vous contacte pour confirmer. Le rendez-vous n’est confirmé qu’après confirmation de la clinique.",
    keywordsAr: ["تأكيد", "حجز"],
    keywordsEn: ["confirm", "booking"],
    keywordsFr: ["confirmation", "réservation"],
  },
  {
    displayOrder: 11,
    slug: "choose-specific-doctor",
    category: "doctors",
    isFeatured: true,
    questionAr: "هل يمكنني اختيار طبيب محدد؟",
    questionEn: "Can I choose a specific doctor?",
    questionFr: "Puis-je choisir un médecin précis ?",
    answerAr: "نعم، يمكنك اختيار طبيب محدد من الأطباء المتاحين للحجز، بشرط أن يقدم الطبيب الخدمة أو التخصص المطلوب وأن يكون لديه موعد متاح.",
    answerEn: "Yes. You can choose a specific doctor from those available for booking, provided they offer the required service or specialty and have an available slot.",
    answerFr: "Oui. Vous pouvez choisir un médecin parmi ceux disponibles à la réservation, s’il propose le service ou la spécialité demandés et dispose d’un créneau.",
    keywordsAr: ["اختيار طبيب"],
    keywordsEn: ["choose doctor"],
    keywordsFr: ["choisir médecin"],
  },
  {
    displayOrder: 12,
    slug: "available-appointment-slots",
    category: "appointments",
    questionAr: "كيف أعرف المواعيد المتاحة؟",
    questionEn: "How do I know which appointment times are available?",
    questionFr: "Comment connaître les créneaux disponibles ?",
    answerAr: "بعد اختيار الطبيب، يعرض نظام الحجز المواعيد المتاحة المسجلة في جدول الطبيب. لا يعرض الموقع مواعيد غير حقيقية أو غير متاحة.",
    answerEn: "After you select a doctor, the booking system shows available slots from that doctor’s schedule. The site does not show fictional or unavailable times.",
    answerFr: "Après avoir choisi un médecin, le système affiche les créneaux disponibles de son agenda. Le site n’affiche pas d’horaires fictifs ou indisponibles.",
    keywordsAr: ["مواعيد متاحة"],
    keywordsEn: ["available slots"],
    keywordsFr: ["créneaux"],
  },
  {
    displayOrder: 13,
    slug: "book-for-family",
    category: "appointments",
    questionAr: "هل يمكنني الحجز لأحد أفراد العائلة؟",
    questionEn: "Can I book for a family member?",
    questionFr: "Puis-je réserver pour un membre de la famille ?",
    answerAr: "نعم، يمكنك الحجز لأحد أفراد العائلة باستخدام بيانات المريض الذي سيزور العيادة، مع إدخال رقم هاتف صالح للتواصل وتأكيد الموعد.",
    answerEn: "Yes. You can book for a family member using the visiting patient’s details and a valid phone number for confirmation.",
    answerFr: "Oui. Vous pouvez réserver pour un proche avec les informations du patient qui se présentera, et un numéro de téléphone valide pour la confirmation.",
    keywordsAr: ["عائلة", "حجز"],
    keywordsEn: ["family", "booking"],
    keywordsFr: ["famille", "réservation"],
  },
  {
    displayOrder: 14,
    slug: "book-for-child",
    category: "pediatric-dentistry",
    questionAr: "هل يمكنني الحجز لطفل؟",
    questionEn: "Can I book for a child?",
    questionFr: "Puis-je réserver pour un enfant ?",
    answerAr: "نعم، يمكن الحجز للطفل واختيار طبيب أو خدمة مناسبة لطب أسنان الأطفال. يجب أن يرافق الطفل وليه أو المسؤول القانوني عنه.",
    answerEn: "Yes. You can book for a child and choose a suitable pediatric dentist or service. A parent or legal guardian should accompany the child.",
    answerFr: "Oui. Vous pouvez réserver pour un enfant et choisir un médecin ou service adapté. Un parent ou tuteur légal doit accompagner l’enfant.",
    keywordsAr: ["طفل", "حجز"],
    keywordsEn: ["child", "booking"],
    keywordsFr: ["enfant", "réservation"],
  },
  {
    displayOrder: 15,
    slug: "email-not-required-for-booking",
    category: "appointments",
    questionAr: "هل أحتاج إلى بريد إلكتروني للحجز؟",
    questionEn: "Do I need an email address to book?",
    questionFr: "Ai-je besoin d’un e-mail pour réserver ?",
    answerAr: "لا يشترط البريد الإلكتروني في نموذج الحجز الحالي. يتم التواصل معك من خلال رقم الهاتف الذي تدخله.",
    answerEn: "Email is not required on the current booking form. We contact you using the phone number you provide.",
    answerFr: "L’e-mail n’est pas requis dans le formulaire actuel. Nous vous contactons via le numéro de téléphone saisi.",
    keywordsAr: ["بريد", "حجز"],
    keywordsEn: ["email", "booking"],
    keywordsFr: ["e-mail", "réservation"],
  },
  {
    displayOrder: 16,
    slug: "no-appointment-confirmation",
    category: "appointments",
    isFeatured: true,
    questionAr: "ماذا أفعل إذا لم يصلني تأكيد الموعد؟",
    questionEn: "What if I do not receive appointment confirmation?",
    questionFr: "Que faire si je ne reçois pas de confirmation ?",
    answerAr: "يمكنك التواصل مع العيادة عبر الهاتف أو واتساب وتزويد الفريق باسم المريض أو مرجع طلب الحجز للتحقق من حالته.",
    answerEn: "Contact the clinic by phone or WhatsApp and share the patient name or booking reference so the team can check the request status.",
    answerFr: "Contactez la clinique par téléphone ou WhatsApp et indiquez le nom du patient ou la référence de la demande afin de vérifier son statut.",
    keywordsAr: ["تأكيد", "لم يصل"],
    keywordsEn: ["confirmation", "missing"],
    keywordsFr: ["confirmation", "manquante"],
  },
  {
    displayOrder: 17,
    slug: "modify-appointment",
    category: "appointments",
    questionAr: "هل يمكنني تعديل موعدي؟",
    questionEn: "Can I modify my appointment?",
    questionFr: "Puis-je modifier mon rendez-vous ?",
    answerAr: "يمكن طلب تعديل الموعد بالتواصل مع فريق العيادة. يعتمد التعديل على توفر مواعيد أخرى لدى الطبيب.",
    answerEn: "You can request a change by contacting the clinic team. Changes depend on other available slots with the doctor.",
    answerFr: "Vous pouvez demander une modification auprès de l’équipe. Elle dépend de la disponibilité d’autres créneaux chez le médecin.",
    keywordsAr: ["تعديل", "موعد"],
    keywordsEn: ["modify", "appointment"],
    keywordsFr: ["modifier", "rendez-vous"],
  },
  {
    displayOrder: 18,
    slug: "cancel-appointment",
    category: "appointments",
    questionAr: "هل يمكنني إلغاء الموعد؟",
    questionEn: "Can I cancel my appointment?",
    questionFr: "Puis-je annuler mon rendez-vous ?",
    answerAr: "نعم، يمكنك طلب إلغاء الموعد من خلال التواصل مع العيادة في أقرب وقت ممكن، حتى يتم إتاحة الموعد لمريض آخر.",
    answerEn: "Yes. Please request cancellation by contacting the clinic as soon as possible so the slot can be offered to another patient.",
    answerFr: "Oui. Contactez la clinique dès que possible pour annuler afin de libérer le créneau pour un autre patient.",
    keywordsAr: ["إلغاء", "موعد"],
    keywordsEn: ["cancel", "appointment"],
    keywordsFr: ["annuler", "rendez-vous"],
  },
  {
    displayOrder: 19,
    slug: "late-for-appointment",
    category: "appointments",
    questionAr: "ماذا يحدث إذا تأخرت عن الموعد؟",
    questionEn: "What happens if I am late?",
    questionFr: "Que se passe-t-il si je suis en retard ?",
    answerAr: "قد يؤدي التأخر إلى تقليل وقت الزيارة أو الحاجة إلى إعادة جدولة الموعد حسب جدول الطبيب. يرجى التواصل مع العيادة عند توقع التأخر.",
    answerEn: "Being late may shorten the visit or require rescheduling depending on the doctor’s schedule. Please contact the clinic if you expect to be late.",
    answerFr: "Un retard peut raccourcir la visite ou nécessiter une reprogrammation selon l’agenda. Contactez la clinique si vous pensez arriver en retard.",
    keywordsAr: ["تأخر", "موعد"],
    keywordsEn: ["late", "delay"],
    keywordsFr: ["retard"],
  },
  {
    displayOrder: 20,
    slug: "arrive-early",
    category: "before-visit",
    questionAr: "كم يجب أن أصل قبل موعدي؟",
    questionEn: "How early should I arrive?",
    questionFr: "Combien de temps à l’avance dois-je arriver ?",
    answerAr: "يفضل الوصول قبل الموعد بنحو 10 إلى 15 دقيقة لإتمام إجراءات الاستقبال وتحديث البيانات عند الحاجة.",
    answerEn: "Please arrive about 10 to 15 minutes early to complete reception steps and update details if needed.",
    answerFr: "Il est préférable d’arriver 10 à 15 minutes avant pour les formalités d’accueil et la mise à jour des informations si besoin.",
    keywordsAr: ["وصول مبكر"],
    keywordsEn: ["arrive early"],
    keywordsFr: ["arriver tôt"],
  },
  {
    displayOrder: 21,
    slug: "choose-right-doctor",
    category: "doctors",
    questionAr: "كيف أختار الطبيب المناسب؟",
    questionEn: "How do I choose the right doctor?",
    questionFr: "Comment choisir le bon médecin ?",
    answerAr: "يمكنك اختيار الطبيب حسب التخصص والخدمة التي تحتاجها، أو التواصل مع فريق العيادة لمساعدتك في اختيار الطبيب المناسب بعد شرح سبب الزيارة بشكل عام.",
    answerEn: "You can choose by specialty and needed service, or contact the clinic team for guidance after briefly describing the reason for the visit.",
    answerFr: "Vous pouvez choisir selon la spécialité et le service, ou contacter l’équipe après avoir décrit brièvement le motif de consultation.",
    keywordsAr: ["اختيار", "طبيب"],
    keywordsEn: ["choose", "doctor"],
    keywordsFr: ["choisir", "médecin"],
  },
  {
    displayOrder: 22,
    slug: "doctors-available-online",
    category: "doctors",
    questionAr: "هل جميع الأطباء متاحون للحجز عبر الموقع؟",
    questionEn: "Are all doctors available for online booking?",
    questionFr: "Tous les médecins sont-ils réservables en ligne ?",
    answerAr: "يعرض الموقع الأطباء النشطين والمتاحين للحجز الإلكتروني فقط. قد يكون بعض الأطباء غير متاحين مؤقتًا بسبب الإجازة أو امتلاء المواعيد.",
    answerEn: "The website lists only active doctors available for online booking. Some may be temporarily unavailable due to leave or a full schedule.",
    answerFr: "Le site n’affiche que les médecins actifs et disponibles à la réservation en ligne. Certains peuvent être temporairement indisponibles.",
    keywordsAr: ["أطباء متاحون"],
    keywordsEn: ["available doctors"],
    keywordsFr: ["médecins disponibles"],
  },
  {
    displayOrder: 23,
    slug: "change-doctor-after-request",
    category: "doctors",
    questionAr: "هل يمكنني تغيير الطبيب بعد إرسال الطلب؟",
    questionEn: "Can I change doctors after submitting a request?",
    questionFr: "Puis-je changer de médecin après la demande ?",
    answerAr: "يمكن طلب تغيير الطبيب قبل تأكيد الموعد، ويعتمد ذلك على توفر الطبيب البديل والخدمة المطلوبة.",
    answerEn: "You can request a doctor change before confirmation, depending on an alternative doctor’s availability and the required service.",
    answerFr: "Vous pouvez demander un changement avant confirmation, selon la disponibilité d’un autre médecin et le service requis.",
    keywordsAr: ["تغيير طبيب"],
    keywordsEn: ["change doctor"],
    keywordsFr: ["changer médecin"],
  },
  {
    displayOrder: 24,
    slug: "doctor-information-page",
    category: "doctors",
    questionAr: "أين أجد معلومات الطبيب؟",
    questionEn: "Where can I find doctor information?",
    questionFr: "Où trouver les informations sur un médecin ?",
    answerAr: "يمكنك فتح صفحة الطبيب للاطلاع على اسمه المهني وتخصصه ونبذته العامة والخدمات التي يقدمها، دون عرض أي معلومات شخصية خاصة.",
    answerEn: "Open the doctor’s page to see professional name, specialty, a general bio, and services offered—without private personal details.",
    answerFr: "Ouvrez la page du médecin pour voir le nom professionnel, la spécialité, une biographie générale et les services, sans données personnelles privées.",
    keywordsAr: ["معلومات طبيب"],
    keywordsEn: ["doctor info"],
    keywordsFr: ["info médecin"],
  },
  {
    displayOrder: 25,
    slug: "what-to-bring",
    category: "before-visit",
    questionAr: "ماذا يجب أن أحضر معي يوم الزيارة؟",
    questionEn: "What should I bring on the day of my visit?",
    questionFr: "Que dois-je apporter le jour de la visite ?",
    answerAr: "يفضل إحضار أي صور أشعة أو تقارير أو وصفات سابقة مرتبطة بالحالة، وقائمة بالأدوية المستخدمة، وأي معلومات صحية مهمة يجب أن يعرفها الطبيب.",
    answerEn: "Bring any related previous X-rays, reports, or prescriptions, a list of medications you take, and important health information the dentist should know.",
    answerFr: "Apportez radiographies, rapports ou ordonnances antérieurs liés, une liste de médicaments, et toute information de santé utile au dentiste.",
    keywordsAr: ["إحضار", "أشعة"],
    keywordsEn: ["bring", "X-ray"],
    keywordsFr: ["apporter", "radio"],
  },
  {
    displayOrder: 26,
    slug: "tell-chronic-conditions",
    category: "before-visit",
    questionAr: "هل يجب أن أخبر الطبيب عن الأمراض المزمنة؟",
    questionEn: "Should I tell the dentist about chronic conditions?",
    questionFr: "Dois-je parler des maladies chroniques ?",
    answerAr: "نعم، يجب إبلاغ الطبيب عن الأمراض المزمنة، والحساسيات، والأدوية، والحمل، والعمليات السابقة، وأي حالة صحية قد تؤثر في العلاج.",
    answerEn: "Yes. Tell the dentist about chronic illnesses, allergies, medications, pregnancy, past surgeries, and any health condition that may affect treatment.",
    answerFr: "Oui. Indiquez maladies chroniques, allergies, médicaments, grossesse, opérations passées et toute condition pouvant influencer le traitement.",
    keywordsAr: ["أمراض مزمنة", "حساسية"],
    keywordsEn: ["chronic", "allergy"],
    keywordsFr: ["chronique", "allergie"],
  },
  {
    displayOrder: 27,
    slug: "eating-before-appointment",
    category: "before-visit",
    questionAr: "هل يجب تناول الطعام قبل موعد الأسنان؟",
    questionEn: "Should I eat before my dental appointment?",
    questionFr: "Dois-je manger avant le rendez-vous ?",
    answerAr: "يعتمد ذلك على نوع العلاج والتعليمات التي يقدمها الطبيب. لا تتوقف عن الأكل أو الأدوية دون تعليمات طبية واضحة.",
    answerEn: "It depends on the treatment and the dentist’s instructions. Do not stop eating or medication without clear medical guidance.",
    answerFr: "Cela dépend du soin et des consignes. N’arrêtez pas alimentation ou médicaments sans indication médicale claire.",
    keywordsAr: ["أكل قبل الموعد"],
    keywordsEn: ["eat before"],
    keywordsFr: ["manger avant"],
  },
  {
    displayOrder: 28,
    slug: "brush-before-visit",
    category: "before-visit",
    questionAr: "هل يجب تنظيف الأسنان قبل الزيارة؟",
    questionEn: "Should I brush my teeth before the visit?",
    questionFr: "Dois-je me brosser les dents avant ?",
    answerAr: "يمكن تنظيف الأسنان كالمعتاد قبل الموعد، لكن لا تؤجل الزيارة بسبب عدم القدرة على تنظيفها، خاصة في حالات الألم أو الطوارئ.",
    answerEn: "You may brush as usual before the appointment, but do not postpone a visit—especially for pain or emergencies—because you could not brush.",
    answerFr: "Vous pouvez vous brosser normalement, mais ne retardez pas une visite—surtout en cas de douleur ou d’urgence—faute de brossage.",
    keywordsAr: ["تنظيف قبل الزيارة"],
    keywordsEn: ["brush before"],
    keywordsFr: ["brossage avant"],
  },
  {
    displayOrder: 29,
    slug: "xrays-before-visit",
    category: "before-visit",
    questionAr: "هل أحتاج إلى أشعة قبل الزيارة؟",
    questionEn: "Do I need X-rays before the visit?",
    questionFr: "Ai-je besoin d’une radio avant la visite ?",
    answerAr: "لا تقم بإجراء أشعة جديدة دون طلب طبي، إلا إذا كانت لديك أشعة سابقة مرتبطة بالحالة فيمكنك إحضارها معك.",
    answerEn: "Do not obtain new X-rays without a clinical request. If you already have related previous images, bring them with you.",
    answerFr: "Ne réalisez pas de nouvelles radios sans demande médicale. Si vous en avez déjà d’anciennes liées, apportez-les.",
    keywordsAr: ["أشعة"],
    keywordsEn: ["X-ray"],
    keywordsFr: ["radio"],
  },
  {
    displayOrder: 30,
    slug: "after-treatment-care",
    category: "after-visit",
    questionAr: "ماذا أفعل بعد العلاج؟",
    questionEn: "What should I do after treatment?",
    questionFr: "Que faire après le traitement ?",
    answerAr: "اتبع التعليمات التي يقدمها الطبيب بعد الزيارة، والتزم بالأدوية والموعد التالي عند وصفهما. تختلف التعليمات حسب نوع العلاج والحالة.",
    answerEn: "Follow the dentist’s post-visit instructions and take prescribed medication and attend follow-ups when advised. Advice varies by treatment and condition.",
    answerFr: "Suivez les consignes du dentiste, prenez les médicaments prescrits et respectez les contrôles. Les consignes varient selon le soin et le cas.",
    keywordsAr: ["بعد العلاج"],
    keywordsEn: ["after treatment"],
    keywordsFr: ["après traitement"],
  },
  {
    displayOrder: 31,
    slug: "eating-after-treatment",
    category: "after-visit",
    questionAr: "متى يمكنني الأكل بعد العلاج؟",
    questionEn: "When can I eat after treatment?",
    questionFr: "Quand manger après le traitement ?",
    answerAr: "تختلف المدة حسب نوع العلاج والتخدير المستخدم. اتبع تعليمات الطبيب، وتجنب الأكل أثناء استمرار تأثير التخدير لتفادي عض الشفاه أو اللسان دون قصد.",
    answerEn: "Timing depends on the procedure and anesthesia used. Follow the dentist’s advice and avoid eating while numbness remains to prevent accidentally biting lips or tongue.",
    answerFr: "Le délai dépend du soin et de l’anesthésie. Suivez les consignes et évitez de manger tant que l’engourdissement persiste pour ne pas vous mordre.",
    keywordsAr: ["أكل بعد"],
    keywordsEn: ["eat after"],
    keywordsFr: ["manger après"],
  },
  {
    displayOrder: 32,
    slug: "pain-after-treatment",
    category: "after-visit",
    questionAr: "ماذا أفعل إذا استمر الألم بعد العلاج؟",
    questionEn: "What if pain continues after treatment?",
    questionFr: "Que faire si la douleur persiste ?",
    answerAr: "قد يحدث انزعاج مؤقت بعد بعض العلاجات، لكن يجب التواصل مع العيادة إذا كان الألم شديدًا أو يزداد أو ترافق مع تورم أو نزيف أو أعراض غير معتادة.",
    answerEn: "Temporary discomfort can occur after some treatments, but contact the clinic if pain is severe, worsening, or accompanied by swelling, bleeding, or unusual symptoms.",
    answerFr: "Un inconfort temporaire est possible, mais contactez la clinique si la douleur est intense, augmente, ou s’accompagne de gonflement, saignement ou symptômes inhabituels.",
    keywordsAr: ["ألم بعد"],
    keywordsEn: ["pain after"],
    keywordsFr: ["douleur après"],
  },
  {
    displayOrder: 33,
    slug: "follow-up-appointment",
    category: "after-visit",
    questionAr: "هل أحتاج إلى موعد متابعة؟",
    questionEn: "Do I need a follow-up appointment?",
    questionFr: "Ai-je besoin d’un contrôle ?",
    answerAr: "يحدد الطبيب الحاجة إلى المتابعة حسب نوع العلاج. قد تتطلب بعض الحالات زيارة إضافية لتقييم الشفاء أو إكمال العلاج.",
    answerEn: "The dentist decides based on the treatment. Some cases need another visit to check healing or complete care.",
    answerFr: "Le dentiste décide selon le soin. Certains cas nécessitent une visite supplémentaire pour évaluer la cicatrisation ou finaliser le traitement.",
    keywordsAr: ["متابعة"],
    keywordsEn: ["follow-up"],
    keywordsFr: ["contrôle"],
  },
  {
    displayOrder: 34,
    slug: "treatment-cost",
    category: "pricing-payment",
    isFeatured: true,
    questionAr: "كم تكلفة العلاج؟",
    questionEn: "How much does treatment cost?",
    questionFr: "Combien coûte le traitement ?",
    answerAr: "تختلف التكلفة حسب التشخيص ونوع العلاج وتعقيد الحالة والمواد المستخدمة. يتم تحديد الخطة والتكلفة المناسبة بعد الفحص الطبي.",
    answerEn: "Cost varies with diagnosis, treatment type, case complexity, and materials. A suitable plan and fee are determined after clinical examination.",
    answerFr: "Le coût dépend du diagnostic, du type de soin, de la complexité et des matériaux. Le plan et le tarif sont précisés après examen.",
    keywordsAr: ["سعر", "تكلفة"],
    keywordsEn: ["price", "cost"],
    keywordsFr: ["prix", "coût"],
  },
  {
    displayOrder: 35,
    slug: "price-before-exam",
    category: "pricing-payment",
    questionAr: "هل يمكن معرفة السعر قبل الفحص؟",
    questionEn: "Can I know the price before an examination?",
    questionFr: "Puis-je connaître le prix avant l’examen ?",
    answerAr: "يمكن تقديم معلومات عامة عن بعض الخدمات، لكن السعر النهائي قد يتطلب فحصًا وتقييمًا للحالة قبل تحديده بدقة.",
    answerEn: "General information about some services can be shared, but a final fee often requires examination and assessment first.",
    answerFr: "Des informations générales peuvent être données, mais le tarif définitif nécessite souvent un examen préalable.",
    keywordsAr: ["سعر قبل الفحص"],
    keywordsEn: ["price before"],
    keywordsFr: ["prix avant"],
  },
  {
    displayOrder: 36,
    slug: "payment-methods",
    category: "pricing-payment",
    questionAr: "ما طرق الدفع المتاحة؟",
    questionEn: "What payment methods are available?",
    questionFr: "Quels modes de paiement sont acceptés ?",
    answerAr: "تعرض العيادة طرق الدفع الفعلية المعتمدة لديها. يرجى التواصل مع فريق العيادة للتأكد من طرق الدفع المتاحة حاليًا.",
    answerEn: "The clinic accepts its currently approved payment methods. Please contact the team to confirm what is available now.",
    answerFr: "La clinique accepte les modes de paiement actuellement validés. Contactez l’équipe pour confirmer ceux disponibles.",
    keywordsAr: ["دفع", "طرق"],
    keywordsEn: ["payment", "methods"],
    keywordsFr: ["paiement", "moyens"],
  },
  {
    displayOrder: 37,
    slug: "initial-consultation",
    category: "pricing-payment",
    questionAr: "هل توجد استشارة أولية؟",
    questionEn: "Is there an initial consultation?",
    questionFr: "Y a-t-il une consultation initiale ?",
    answerAr: "تتوفر خدمات الفحص والاستشارة حسب جدول الأطباء والخدمات المسجلة في العيادة. يمكنك اختيار خدمة الفحص أو التواصل معنا للمساعدة.",
    answerEn: "Examination and consultation services depend on doctors’ schedules and clinic offerings. You can select an exam service or contact us for help.",
    answerFr: "Les examens et consultations dépendent des agendas et des services. Vous pouvez choisir un examen ou nous contacter.",
    keywordsAr: ["استشارة", "فحص"],
    keywordsEn: ["consultation", "exam"],
    keywordsFr: ["consultation", "examen"],
  },
  {
    displayOrder: 38,
    slug: "when-dental-exam",
    category: "general-dentistry",
    questionAr: "متى أحتاج إلى فحص الأسنان؟",
    questionEn: "When do I need a dental examination?",
    questionFr: "Quand faut-il un examen dentaire ?",
    answerAr: "ينصح بالفحص عند وجود ألم أو حساسية أو نزيف لثة أو كسر أو تسوس ظاهر أو رائحة فم مستمرة، كما يمكن إجراء فحوصات دورية للوقاية والكشف المبكر.",
    answerEn: "An exam is recommended for pain, sensitivity, gum bleeding, fracture, visible decay, or persistent bad breath, and also for routine preventive check-ups.",
    answerFr: "Un examen est conseillé en cas de douleur, sensibilité, saignement gingival, fracture, carie visible ou mauvaise haleine persistante, ainsi que pour le suivi préventif.",
    keywordsAr: ["فحص", "ألم"],
    keywordsEn: ["exam", "pain"],
    keywordsFr: ["examen", "douleur"],
  },
  {
    displayOrder: 39,
    slug: "during-dental-exam",
    category: "general-dentistry",
    questionAr: "ماذا يحدث أثناء فحص الأسنان؟",
    questionEn: "What happens during a dental examination?",
    questionFr: "Que se passe-t-il pendant l’examen ?",
    answerAr: "يفحص الطبيب الأسنان واللثة والفم، ويسأل عن الأعراض والتاريخ الصحي، وقد يطلب أشعة أو فحوصات إضافية عند الحاجة.",
    answerEn: "The dentist examines teeth, gums, and mouth, asks about symptoms and health history, and may request X-rays or further tests when needed.",
    answerFr: "Le dentiste examine dents, gencives et bouche, interroge sur les symptômes et l’historique, et peut demander des radios ou d’autres examens.",
    keywordsAr: ["فحص أسنان"],
    keywordsEn: ["dental exam"],
    keywordsFr: ["examen dentaire"],
  },
  {
    displayOrder: 40,
    slug: "is-exam-painful",
    category: "general-dentistry",
    questionAr: "هل الفحص مؤلم؟",
    questionEn: "Is a dental exam painful?",
    questionFr: "L’examen est-il douloureux ?",
    answerAr: "الفحص العادي غالبًا لا يسبب ألمًا، لكن قد تشعر بانزعاج إذا كانت المنطقة ملتهبة أو شديدة الحساسية. أخبر الطبيب عند الشعور بأي ألم.",
    answerEn: "A routine exam is usually not painful, though discomfort may occur if an area is inflamed or very sensitive. Tell the dentist if you feel pain.",
    answerFr: "Un examen habituel n’est généralement pas douloureux, mais un inconfort est possible si la zone est inflammée ou très sensible. Signalez toute douleur.",
    keywordsAr: ["ألم فحص"],
    keywordsEn: ["exam pain"],
    keywordsFr: ["douleur examen"],
  },
  {
    displayOrder: 41,
    slug: "cleaning-vs-brushing",
    category: "cleaning-gums",
    questionAr: "ما الفرق بين تنظيف الأسنان وتنظيفها اليومي بالفرشاة؟",
    questionEn: "What is the difference between professional cleaning and daily brushing?",
    questionFr: "Quelle différence entre nettoyage professionnel et brossage ?",
    answerAr: "التنظيف اليومي يساعد على إزالة بقايا الطعام واللويحة السطحية، بينما يزيل التنظيف داخل العيادة الجير والترسبات التي لا يمكن للفرشاة إزالتها.",
    answerEn: "Daily brushing helps remove food debris and surface plaque, while professional cleaning removes tartar and deposits that a toothbrush cannot remove.",
    answerFr: "Le brossage quotidien enlève débris et plaque superficielle ; le nettoyage en cabinet enlève le tartre que la brosse ne peut pas retirer.",
    keywordsAr: ["تنظيف", "جير"],
    keywordsEn: ["cleaning", "tartar"],
    keywordsFr: ["nettoyage", "tartre"],
  },
  {
    displayOrder: 42,
    slug: "cleaning-enamel-safe",
    category: "cleaning-gums",
    questionAr: "هل تنظيف الأسنان يضر بالمينا؟",
    questionEn: "Does professional cleaning damage enamel?",
    questionFr: "Le nettoyage endommage-t-il l’émail ?",
    answerAr: "عند إجرائه بطريقة مهنية مناسبة، يهدف التنظيف إلى إزالة الجير والترسبات دون الإضرار بالمينا.",
    answerEn: "When performed professionally and appropriately, cleaning aims to remove tartar and deposits without damaging enamel.",
    answerFr: "Réalisé de façon professionnelle adaptée, il vise à retirer tartre et dépôts sans abîmer l’émail.",
    keywordsAr: ["مينا", "تنظيف"],
    keywordsEn: ["enamel", "cleaning"],
    keywordsFr: ["émail", "nettoyage"],
  },
  {
    displayOrder: 43,
    slug: "is-cleaning-painful",
    category: "cleaning-gums",
    questionAr: "هل تنظيف الأسنان مؤلم؟",
    questionEn: "Is teeth cleaning painful?",
    questionFr: "Le nettoyage est-il douloureux ?",
    answerAr: "قد يشعر بعض المرضى بحساسية أو انزعاج بسيط، خاصة عند وجود التهاب في اللثة أو تراكم كبير للجير. يمكن للطبيب تعديل الإجراء حسب الحالة.",
    answerEn: "Some patients feel mild sensitivity or discomfort, especially with gum inflammation or heavy tartar. The dentist can adjust the procedure as needed.",
    answerFr: "Certains ressentent une sensibilité ou un léger inconfort, surtout en cas d’inflammation ou de tartre important. Le dentiste peut adapter le geste.",
    keywordsAr: ["ألم تنظيف"],
    keywordsEn: ["cleaning pain"],
    keywordsFr: ["douleur nettoyage"],
  },
  {
    displayOrder: 44,
    slug: "how-often-cleaning",
    category: "cleaning-gums",
    questionAr: "كم مرة أحتاج إلى تنظيف الأسنان؟",
    questionEn: "How often do I need professional cleaning?",
    questionFr: "À quelle fréquence se faire nettoyer les dents ?",
    answerAr: "تختلف الحاجة حسب صحة اللثة، وتراكم الجير، والعناية اليومية، والتدخين، وبعض الحالات الصحية. يحدد الطبيب الفترة المناسبة لكل مريض.",
    answerEn: "Need varies with gum health, tartar buildup, daily care, smoking, and some health conditions. The dentist recommends a suitable interval for each patient.",
    answerFr: "Cela dépend de la santé gingivale, du tartre, de l’hygiène, du tabac et de certains états de santé. Le dentiste propose un rythme adapté.",
    keywordsAr: ["مرات تنظيف"],
    keywordsEn: ["cleaning frequency"],
    keywordsFr: ["fréquence nettoyage"],
  },
  {
    displayOrder: 45,
    slug: "gum-bleeding",
    category: "cleaning-gums",
    questionAr: "هل نزيف اللثة طبيعي؟",
    questionEn: "Is gum bleeding normal?",
    questionFr: "Le saignement des gencives est-il normal ?",
    answerAr: "نزيف اللثة المتكرر قد يكون علامة على التهاب أو مشكلة تحتاج إلى تقييم. لا تتجاهله، خاصة إذا استمر أو ترافق مع تورم أو رائحة فم.",
    answerEn: "Recurring gum bleeding may indicate inflammation or a problem needing assessment. Do not ignore it, especially if it persists or comes with swelling or bad breath.",
    answerFr: "Un saignement répété peut indiquer une inflammation à évaluer. Ne l’ignorez pas, surtout s’il persiste avec gonflement ou mauvaise haleine.",
    keywordsAr: ["نزيف لثة"],
    keywordsEn: ["gum bleeding"],
    keywordsFr: ["saignement gencives"],
  },
  {
    displayOrder: 46,
    slug: "bad-breath-cleaning",
    category: "cleaning-gums",
    questionAr: "هل يمكن علاج رائحة الفم بتنظيف الأسنان؟",
    questionEn: "Can cleaning treat bad breath?",
    questionFr: "Le nettoyage traite-t-il la mauvaise haleine ?",
    answerAr: "قد يساعد التنظيف إذا كانت الرائحة مرتبطة بالجير أو التهاب اللثة، لكن رائحة الفم قد تكون لها أسباب أخرى تحتاج إلى تقييم.",
    answerEn: "Cleaning may help if the odor relates to tartar or gum inflammation, but bad breath can have other causes needing evaluation.",
    answerFr: "Il peut aider si l’odeur est liée au tartre ou à une inflammation gingivale, mais d’autres causes peuvent nécessiter une évaluation.",
    keywordsAr: ["رائحة فم"],
    keywordsEn: ["bad breath"],
    keywordsFr: ["haleine"],
  },
  {
    displayOrder: 47,
    slug: "what-is-whitening",
    category: "teeth-whitening",
    questionAr: "ما هو تبييض الأسنان؟",
    questionEn: "What is teeth whitening?",
    questionFr: "Qu’est-ce que le blanchiment dentaire ?",
    answerAr: "تبييض الأسنان إجراء تجميلي يهدف إلى تحسين لون الأسنان باستخدام مواد وتقنيات مناسبة بعد تقييم الأسنان واللثة.",
    answerEn: "Teeth whitening is a cosmetic procedure that aims to improve tooth shade using suitable materials and techniques after assessing teeth and gums.",
    answerFr: "C’est un soin esthétique visant à éclaircir la teinte des dents avec des matériaux et techniques adaptés après évaluation dents et gencives.",
    keywordsAr: ["تبييض"],
    keywordsEn: ["whitening"],
    keywordsFr: ["blanchiment"],
  },
  {
    displayOrder: 48,
    slug: "whitening-for-everyone",
    category: "teeth-whitening",
    questionAr: "هل تبييض الأسنان مناسب للجميع؟",
    questionEn: "Is whitening suitable for everyone?",
    questionFr: "Le blanchiment convient-il à tous ?",
    answerAr: "ليس مناسبًا لجميع الحالات. يجب تقييم التسوس والحشوات والتيجان وحساسية الأسنان وصحة اللثة قبل اتخاذ القرار.",
    answerEn: "Not for every case. Decay, fillings, crowns, tooth sensitivity, and gum health should be assessed before deciding.",
    answerFr: "Pas à tous les cas. Caries, obturations, couronnes, sensibilité et santé gingivale doivent être évaluées avant de décider.",
    keywordsAr: ["مناسب تبييض"],
    keywordsEn: ["whitening suitable"],
    keywordsFr: ["blanchiment adapté"],
  },
  {
    displayOrder: 49,
    slug: "whitening-sensitivity",
    category: "teeth-whitening",
    questionAr: "هل تبييض الأسنان يسبب الحساسية؟",
    questionEn: "Can whitening cause sensitivity?",
    questionFr: "Le blanchiment cause-t-il une sensibilité ?",
    answerAr: "قد تحدث حساسية مؤقتة لدى بعض الأشخاص. يختار الطبيب التركيز والطريقة المناسبة ويقدم تعليمات لتقليل الحساسية.",
    answerEn: "Temporary sensitivity can occur. The dentist chooses suitable concentration and method and gives advice to reduce sensitivity.",
    answerFr: "Une sensibilité temporaire est possible. Le dentiste choisit concentration et méthode et donne des conseils pour la limiter.",
    keywordsAr: ["حساسية تبييض"],
    keywordsEn: ["whitening sensitivity"],
    keywordsFr: ["sensibilité blanchiment"],
  },
  {
    displayOrder: 50,
    slug: "whitening-results-lasting",
    category: "teeth-whitening",
    questionAr: "هل نتيجة التبييض دائمة؟",
    questionEn: "Are whitening results permanent?",
    questionFr: "Le résultat du blanchiment est-il permanent ?",
    answerAr: "ليست دائمة عادةً، وقد يتغير اللون مع الوقت بسبب العادات الغذائية والتدخين والعناية اليومية. تختلف النتيجة والمدة من شخص إلى آخر.",
    answerEn: "Usually not permanent. Shade can change over time with diet, smoking, and daily care. Results and duration vary between people.",
    answerFr: "En général non. La teinte peut évoluer avec l’alimentation, le tabac et l’hygiène. Résultat et durée varient selon les personnes.",
    keywordsAr: ["نتيجة تبييض"],
    keywordsEn: ["whitening results"],
    keywordsFr: ["résultat blanchiment"],
  },
  {
    displayOrder: 51,
    slug: "whitening-fillings-crowns",
    category: "teeth-whitening",
    questionAr: "هل يغيّر التبييض لون الحشوات والتيجان؟",
    questionEn: "Does whitening change the color of fillings and crowns?",
    questionFr: "Le blanchiment change-t-il obturations et couronnes ?",
    answerAr: "مواد التبييض لا تغيّر عادةً لون الحشوات أو التيجان مثل الأسنان الطبيعية، لذلك يجب تقييم تطابق الألوان قبل العلاج.",
    answerEn: "Whitening agents usually do not change fillings or crowns like natural teeth, so shade matching should be assessed beforehand.",
    answerFr: "Les agents ne modifient généralement pas la teinte des obturations ou couronnes comme celle des dents naturelles ; l’harmonie des teintes doit être évaluée avant.",
    keywordsAr: ["حشوات تبييض"],
    keywordsEn: ["whitening crowns"],
    keywordsFr: ["blanchiment couronnes"],
  },
  {
    displayOrder: 52,
    slug: "when-need-filling",
    category: "fillings",
    questionAr: "متى أحتاج إلى حشوة؟",
    questionEn: "When do I need a filling?",
    questionFr: "Quand faut-il une obturation ?",
    answerAr: "قد تحتاج إلى حشوة عند وجود تسوس أو كسر أو فقدان جزء من السن. يحدد الطبيب نوع الترميم المناسب بعد الفحص.",
    answerEn: "A filling may be needed for decay, fracture, or loss of tooth structure. The dentist chooses a suitable restoration after examination.",
    answerFr: "Une obturation peut être nécessaire en cas de carie, fracture ou perte de substance. Le dentiste choisit la restauration après examen.",
    keywordsAr: ["حشوة", "تسوس"],
    keywordsEn: ["filling", "decay"],
    keywordsFr: ["obturation", "carie"],
  },
  {
    displayOrder: 53,
    slug: "filling-pain",
    category: "fillings",
    questionAr: "هل الحشوة تسبب الألم؟",
    questionEn: "Do fillings cause pain?",
    questionFr: "L’obturation est-elle douloureuse ?",
    answerAr: "يتم العلاج عادةً باستخدام تخدير موضعي عند الحاجة. قد تحدث حساسية مؤقتة بعد الحشو، ويجب التواصل مع الطبيب إذا استمرت أو ازدادت.",
    answerEn: "Treatment usually uses local anesthesia when needed. Temporary sensitivity can follow; contact the dentist if it persists or worsens.",
    answerFr: "Une anesthésie locale est souvent utilisée si besoin. Une sensibilité temporaire peut suivre ; contactez le dentiste si elle persiste ou s’aggrave.",
    keywordsAr: ["ألم حشوة"],
    keywordsEn: ["filling pain"],
    keywordsFr: ["douleur obturation"],
  },
  {
    displayOrder: 54,
    slug: "filling-longevity",
    category: "fillings",
    questionAr: "كم تدوم حشوة الأسنان؟",
    questionEn: "How long do fillings last?",
    questionFr: "Combien de temps dure une obturation ?",
    answerAr: "تختلف مدة الحشوة حسب نوع المادة وحجم الحشوة ومكانها وقوة الإطباق والعناية اليومية. تحتاج الحشوات إلى فحص دوري.",
    answerEn: "Longevity depends on material, size, location, bite forces, and daily care. Fillings need periodic examination.",
    answerFr: "La durée dépend du matériau, de la taille, de l’emplacement, de l’occlusion et de l’hygiène. Un contrôle périodique est nécessaire.",
    keywordsAr: ["عمر حشوة"],
    keywordsEn: ["filling longevity"],
    keywordsFr: ["durée obturation"],
  },
  {
    displayOrder: 55,
    slug: "fallen-filling",
    category: "fillings",
    questionAr: "ماذا أفعل إذا سقطت الحشوة؟",
    questionEn: "What if a filling falls out?",
    questionFr: "Que faire si une obturation tombe ?",
    answerAr: "تجنب المضغ على السن المتضرر واتصل بالعيادة لتقييم الحالة. لا تحاول وضع مواد منزلية داخل السن.",
    answerEn: "Avoid chewing on the affected tooth and contact the clinic for assessment. Do not place home materials inside the tooth.",
    answerFr: "Évitez de mâcher de ce côté et contactez la clinique. N’introduisez pas de matériaux domestiques dans la dent.",
    keywordsAr: ["سقوط حشوة"],
    keywordsEn: ["fallen filling"],
    keywordsFr: ["obturation tombée"],
  },
  {
    displayOrder: 56,
    slug: "when-root-canal",
    category: "root-canal",
    questionAr: "متى يحتاج السن إلى علاج العصب؟",
    questionEn: "When does a tooth need root canal treatment?",
    questionFr: "Quand faut-il un traitement de canal ?",
    answerAr: "قد يحتاج السن إلى علاج العصب عند وصول الالتهاب أو العدوى إلى لب السن، أو عند وجود ألم شديد أو خراج أو تلف عميق. يعتمد القرار على الفحص والأشعة.",
    answerEn: "A tooth may need root canal care when inflammation or infection reaches the pulp, or with severe pain, abscess, or deep damage. Decision depends on exam and imaging.",
    answerFr: "Il peut être indiqué si inflammation ou infection atteint la pulpe, ou en cas de douleur intense, abcès ou lésion profonde. La décision repose sur l’examen et l’imagerie.",
    keywordsAr: ["علاج عصب"],
    keywordsEn: ["root canal"],
    keywordsFr: ["canal"],
  },
  {
    displayOrder: 57,
    slug: "root-canal-pain",
    category: "root-canal",
    questionAr: "هل علاج العصب مؤلم؟",
    questionEn: "Is root canal treatment painful?",
    questionFr: "Le traitement de canal est-il douloureux ?",
    answerAr: "يتم العلاج عادةً تحت التخدير الموضعي. قد يحدث انزعاج مؤقت بعد الجلسة، لكن الهدف من العلاج هو إزالة سبب الألم والعدوى.",
    answerEn: "It is usually done under local anesthesia. Temporary discomfort can follow, but the goal is to remove the cause of pain and infection.",
    answerFr: "Il se fait généralement sous anesthésie locale. Un inconfort temporaire peut suivre, le but étant de traiter la cause de la douleur et de l’infection.",
    keywordsAr: ["ألم عصب"],
    keywordsEn: ["root canal pain"],
    keywordsFr: ["douleur canal"],
  },
  {
    displayOrder: 58,
    slug: "root-canal-sessions",
    category: "root-canal",
    questionAr: "كم جلسة يحتاج علاج العصب؟",
    questionEn: "How many sessions does a root canal need?",
    questionFr: "Combien de séances pour un canal ?",
    answerAr: "قد يتم العلاج في جلسة واحدة أو أكثر حسب حالة السن ووجود التهاب أو عدوى وتعقيد القنوات.",
    answerEn: "Treatment may take one or more visits depending on tooth condition, inflammation or infection, and canal complexity.",
    answerFr: "Une ou plusieurs séances selon l’état de la dent, l’inflammation ou l’infection, et la complexité des canaux.",
    keywordsAr: ["جلسات عصب"],
    keywordsEn: ["root canal sessions"],
    keywordsFr: ["séances canal"],
  },
  {
    displayOrder: 59,
    slug: "crown-after-root-canal",
    category: "root-canal",
    questionAr: "هل يحتاج السن إلى تاج بعد علاج العصب؟",
    questionEn: "Does a tooth need a crown after root canal?",
    questionFr: "Faut-il une couronne après un canal ?",
    answerAr: "قد يحتاج بعض الأسنان، خاصة الأسنان الخلفية، إلى تاج لحمايتها من الكسر بعد علاج العصب. يحدد الطبيب الحاجة حسب كمية بنية السن المتبقية.",
    answerEn: "Some teeth, especially back teeth, may need a crown for protection after root canal. The dentist decides based on remaining tooth structure.",
    answerFr: "Certaines dents, surtout postérieures, peuvent nécessiter une couronne de protection. Le dentiste décide selon la structure restante.",
    keywordsAr: ["تاج بعد عصب"],
    keywordsEn: ["crown after canal"],
    keywordsFr: ["couronne après canal"],
  },
  {
    displayOrder: 60,
    slug: "when-extraction",
    category: "extraction",
    questionAr: "متى يكون خلع السن ضروريًا؟",
    questionEn: "When is tooth extraction necessary?",
    questionFr: "Quand une extraction est-elle nécessaire ?",
    answerAr: "يتم التفكير في الخلع عندما يتعذر الحفاظ على السن أو عند وجود تلف شديد أو عدوى أو مشكلة تقويمية أو ضرس عقل يحتاج إلى الإزالة. يقرر الطبيب بعد التقييم.",
    answerEn: "Extraction is considered when a tooth cannot be saved, or with severe damage, infection, orthodontic needs, or a wisdom tooth requiring removal. The dentist decides after assessment.",
    answerFr: "Elle est envisagée si la dent ne peut être conservée, ou en cas de lésion sévère, infection, besoin orthodontique ou dent de sagesse à retirer. Décision après évaluation.",
    keywordsAr: ["خلع"],
    keywordsEn: ["extraction"],
    keywordsFr: ["extraction"],
  },
  {
    displayOrder: 61,
    slug: "after-extraction-care",
    category: "extraction",
    questionAr: "ماذا أفعل بعد خلع السن؟",
    questionEn: "What should I do after an extraction?",
    questionFr: "Que faire après une extraction ?",
    answerAr: "اتبع تعليمات الطبيب، واضغط على الشاش حسب المدة المحددة، وتجنب المضمضة القوية والتدخين والمشروبات الساخنة في الفترة الأولى.",
    answerEn: "Follow the dentist’s instructions, bite on gauze for the advised time, and avoid forceful rinsing, smoking, and hot drinks in the early period.",
    answerFr: "Suivez les consignes, comprimez la gaze le temps indiqué, et évitez rinçages forts, tabac et boissons chaudes au début.",
    keywordsAr: ["بعد خلع"],
    keywordsEn: ["after extraction"],
    keywordsFr: ["après extraction"],
  },
  {
    displayOrder: 62,
    slug: "contact-after-extraction",
    category: "extraction",
    questionAr: "متى يجب أن أتواصل مع العيادة بعد الخلع؟",
    questionEn: "When should I contact the clinic after extraction?",
    questionFr: "Quand contacter la clinique après extraction ?",
    answerAr: "تواصل مع العيادة عند وجود نزيف لا يتوقف، أو ألم شديد يزداد، أو تورم كبير، أو حرارة، أو صعوبة في التنفس أو البلع.",
    answerEn: "Contact the clinic for bleeding that does not stop, worsening severe pain, large swelling, fever, or difficulty breathing or swallowing.",
    answerFr: "Contactez en cas de saignement qui ne s’arrête pas, douleur intense qui augmente, gros gonflement, fièvre, ou difficulté à respirer ou avaler.",
    keywordsAr: ["طوارئ خلع"],
    keywordsEn: ["extraction emergency"],
    keywordsFr: ["urgence extraction"],
  },
  {
    displayOrder: 63,
    slug: "wisdom-always-remove",
    category: "wisdom-teeth",
    questionAr: "هل يجب خلع ضرس العقل دائمًا؟",
    questionEn: "Must wisdom teeth always be removed?",
    questionFr: "Faut-il toujours extraire les dents de sagesse ?",
    answerAr: "لا. يتم خلع ضرس العقل عندما يسبب مشكلة مثل الألم أو الالتهاب أو التسوس أو الضغط أو الانطمار، أو عندما يرى الطبيب ضرورة لذلك بعد الفحص والأشعة.",
    answerEn: "No. Removal is considered when they cause problems such as pain, inflammation, decay, pressure, or impaction, or when the dentist judges it necessary after exam and imaging.",
    answerFr: "Non. L’extraction est envisagée si elles posent problème (douleur, inflammation, carie, pression, inclusion) ou si le dentiste le juge nécessaire après examen et imagerie.",
    keywordsAr: ["ضرس عقل"],
    keywordsEn: ["wisdom tooth"],
    keywordsFr: ["dent de sagesse"],
  },
  {
    displayOrder: 64,
    slug: "wisdom-tooth-signs",
    category: "wisdom-teeth",
    questionAr: "ما علامات مشكلة ضرس العقل؟",
    questionEn: "What are signs of a wisdom tooth problem?",
    questionFr: "Quels signes d’un problème de dent de sagesse ?",
    answerAr: "قد تشمل الألم خلف الفك، تورم اللثة، صعوبة فتح الفم، التهاب متكرر، طعم غير طبيعي أو ألم يمتد إلى الأذن أو الفك.",
    answerEn: "Signs may include pain behind the jaw, gum swelling, difficulty opening the mouth, recurrent inflammation, unusual taste, or pain radiating to the ear or jaw.",
    answerFr: "Douleur derrière la mâchoire, gonflement gingival, difficulté à ouvrir la bouche, inflammation répétée, goût inhabituel ou douleur vers l’oreille ou la mâchoire.",
    keywordsAr: ["علامات ضرس عقل"],
    keywordsEn: ["wisdom signs"],
    keywordsFr: ["signes sagesse"],
  },
  {
    displayOrder: 65,
    slug: "wisdom-surgical",
    category: "wisdom-teeth",
    questionAr: "هل خلع ضرس العقل جراحي؟",
    questionEn: "Is wisdom tooth removal surgical?",
    questionFr: "L’extraction de dent de sagesse est-elle chirurgicale ?",
    answerAr: "بعض ضروس العقل تخلع بطريقة عادية، بينما تحتاج الحالات المنطمرة أو المعقدة إلى إجراء جراحي. يحدد الطبيب الطريقة بعد الأشعة.",
    answerEn: "Some wisdom teeth are removed routinely; impacted or complex cases may need a surgical approach. The dentist decides after imaging.",
    answerFr: "Certaines s’extraient de façon classique ; les inclusions ou cas complexes peuvent nécessiter un geste chirurgical. Décision après imagerie.",
    keywordsAr: ["خلع جراحي"],
    keywordsEn: ["surgical extraction"],
    keywordsFr: ["extraction chirurgicale"],
  },
  {
    displayOrder: 66,
    slug: "what-is-implant",
    category: "implants",
    questionAr: "ما هي زراعة الأسنان؟",
    questionEn: "What are dental implants?",
    questionFr: "Qu’est-ce qu’un implant dentaire ?",
    answerAr: "زراعة الأسنان وسيلة لتعويض الأسنان المفقودة باستخدام غرسة تثبت في العظم ثم يركب عليها التعويض المناسب بعد التقييم والالتئام.",
    answerEn: "Dental implants replace missing teeth with a fixture placed in bone, then an appropriate restoration after assessment and healing.",
    answerFr: "C’est un moyen de remplacer des dents absentes par une fixture osseuse puis une restauration adaptée après évaluation et cicatrisation.",
    keywordsAr: ["زراعة"],
    keywordsEn: ["implant"],
    keywordsFr: ["implant"],
  },
  {
    displayOrder: 67,
    slug: "implants-for-everyone",
    category: "implants",
    questionAr: "هل زراعة الأسنان مناسبة للجميع؟",
    questionEn: "Are implants suitable for everyone?",
    questionFr: "Les implants conviennent-ils à tous ?",
    answerAr: "تحتاج الزراعة إلى تقييم صحة الفم واللثة والعظم والحالة الصحية العامة والتدخين والأدوية. لا يمكن تحديد ملاءمتها دون فحص.",
    answerEn: "Implants require assessment of oral and gum health, bone, general health, smoking, and medications. Suitability cannot be decided without examination.",
    answerFr: "Ils nécessitent une évaluation bouche, gencives, os, santé générale, tabac et médicaments. Sans examen, on ne peut pas conclure.",
    keywordsAr: ["مناسب زراعة"],
    keywordsEn: ["implant suitable"],
    keywordsFr: ["implant adapté"],
  },
  {
    displayOrder: 68,
    slug: "implant-duration",
    category: "implants",
    questionAr: "كم تستغرق زراعة الأسنان؟",
    questionEn: "How long does implant treatment take?",
    questionFr: "Combien de temps dure un implant ?",
    answerAr: "تختلف المدة حسب حالة العظم واللثة والحاجة إلى إجراءات إضافية وفترة الالتئام. يوضح الطبيب الخطة الزمنية بعد الفحص.",
    answerEn: "Duration varies with bone and gum condition, additional procedures, and healing time. The dentist explains the timeline after examination.",
    answerFr: "La durée dépend de l’os, des gencives, d’éventuels actes associés et de la cicatrisation. Le dentiste précise le calendrier après examen.",
    keywordsAr: ["مدة زراعة"],
    keywordsEn: ["implant duration"],
    keywordsFr: ["durée implant"],
  },
  {
    displayOrder: 69,
    slug: "implant-care",
    category: "implants",
    questionAr: "كيف أعتني بزراعة الأسنان؟",
    questionEn: "How do I care for dental implants?",
    questionFr: "Comment entretenir un implant ?",
    answerAr: "تحتاج الزراعة إلى تنظيف يومي جيد وفحوصات دورية والعناية باللثة وتجنب العادات الضارة، مثلها مثل الأسنان الطبيعية.",
    answerEn: "Implants need good daily cleaning, periodic check-ups, gum care, and avoidance of harmful habits—like natural teeth.",
    answerFr: "Il faut un nettoyage quotidien, des contrôles, le soin des gencives et éviter les habitudes nocives, comme pour les dents naturelles.",
    keywordsAr: ["عناية زراعة"],
    keywordsEn: ["implant care"],
    keywordsFr: ["entretien implant"],
  },
  {
    displayOrder: 70,
    slug: "what-is-crown",
    category: "crowns-bridges",
    questionAr: "ما هو تاج الأسنان؟",
    questionEn: "What is a dental crown?",
    questionFr: "Qu’est-ce qu’une couronne dentaire ?",
    answerAr: "التاج غطاء يثبت على السن لحمايته أو استعادة شكله ووظيفته عندما يكون متضررًا أو ضعيفًا.",
    answerEn: "A crown is a cover cemented onto a tooth to protect it or restore shape and function when the tooth is damaged or weakened.",
    answerFr: "C’est une coiffe fixée sur une dent pour la protéger ou restaurer forme et fonction lorsqu’elle est abîmée ou fragilisée.",
    keywordsAr: ["تاج"],
    keywordsEn: ["crown"],
    keywordsFr: ["couronne"],
  },
  {
    displayOrder: 71,
    slug: "when-bridge",
    category: "crowns-bridges",
    questionAr: "متى أحتاج إلى جسر أسنان؟",
    questionEn: "When do I need a dental bridge?",
    questionFr: "Quand faut-il un bridge ?",
    answerAr: "قد يستخدم الجسر لتعويض سن أو أكثر من الأسنان المفقودة بالاعتماد على الأسنان المجاورة أو حسب الخطة العلاجية المناسبة.",
    answerEn: "A bridge may replace one or more missing teeth using neighboring teeth, or according to the suitable treatment plan.",
    answerFr: "Un bridge peut remplacer une ou plusieurs dents absentes en s’appuyant sur les dents voisines, selon le plan adapté.",
    keywordsAr: ["جسر"],
    keywordsEn: ["bridge"],
    keywordsFr: ["bridge"],
  },
  {
    displayOrder: 72,
    slug: "crowns-bridges-longevity",
    category: "crowns-bridges",
    questionAr: "كم تدوم التيجان والجسور؟",
    questionEn: "How long do crowns and bridges last?",
    questionFr: "Combien de temps durent couronnes et bridges ?",
    answerAr: "تعتمد المدة على المادة والعناية اليومية وصحة اللثة والإطباق والعادات مثل صرير الأسنان. تحتاج إلى متابعة دورية.",
    answerEn: "Longevity depends on material, daily care, gum health, bite, and habits such as grinding. Periodic follow-up is needed.",
    answerFr: "Cela dépend du matériau, de l’hygiène, des gencives, de l’occlusion et d’habitudes comme le bruxisme. Un suivi périodique est nécessaire.",
    keywordsAr: ["عمر تاج"],
    keywordsEn: ["crown longevity"],
    keywordsFr: ["durée couronne"],
  },
  {
    displayOrder: 73,
    slug: "when-orthodontics",
    category: "orthodontics",
    questionAr: "متى أحتاج إلى تقويم الأسنان؟",
    questionEn: "When do I need orthodontics?",
    questionFr: "Quand faut-il une orthodontie ?",
    answerAr: "قد يكون التقويم مناسبًا عند وجود ازدحام أو فراغات أو عدم انتظام الأسنان أو مشاكل في الإطباق. يحتاج القرار إلى فحص وتقويم كامل.",
    answerEn: "Orthodontics may help with crowding, spacing, irregular teeth, or bite problems. Decision requires a full examination and orthodontic assessment.",
    answerFr: "Elle peut convenir en cas d’encombrement, d’espaces, d’irrégularité ou de troubles d’occlusion. La décision nécessite un examen et un bilan orthodontiques.",
    keywordsAr: ["تقويم"],
    keywordsEn: ["orthodontics"],
    keywordsFr: ["orthodontie"],
    relatedSpecialtySlugs: ["orthodontics"],
  },
  {
    displayOrder: 74,
    slug: "orthodontics-adults",
    category: "orthodontics",
    questionAr: "هل تقويم الأسنان مناسب للبالغين؟",
    questionEn: "Is orthodontics suitable for adults?",
    questionFr: "L’orthodontie convient-elle aux adultes ?",
    answerAr: "يمكن للبالغين الاستفادة من التقويم عندما تكون صحة الأسنان واللثة مناسبة، ويحدد الطبيب النوع والخطة حسب الحالة.",
    answerEn: "Adults can benefit when teeth and gum health are suitable. The dentist chooses type and plan based on the case.",
    answerFr: "Les adultes peuvent en bénéficier si dents et gencives le permettent. Le type et le plan sont choisis selon le cas.",
    keywordsAr: ["تقويم بالغين"],
    keywordsEn: ["adult braces"],
    keywordsFr: ["adulte orthodontie"],
  },
  {
    displayOrder: 75,
    slug: "fixed-vs-clear-aligners",
    category: "orthodontics",
    questionAr: "ما الفرق بين التقويم الثابت والشفاف؟",
    questionEn: "What is the difference between fixed braces and clear aligners?",
    questionFr: "Différence entre appareil fixe et aligneurs ?",
    answerAr: "التقويم الثابت يستخدم حاصرات وأسلاكًا، بينما يعتمد التقويم الشفاف على قوالب متحركة. تختلف الملاءمة والمدة حسب الحالة والالتزام.",
    answerEn: "Fixed braces use brackets and wires; clear aligners use removable trays. Suitability and duration depend on the case and compliance.",
    answerFr: "L’appareil fixe utilise bagues et fils ; les aligneurs sont des gouttières amovibles. Adaptation et durée dépendent du cas et de l’observance.",
    keywordsAr: ["تقويم شفاف"],
    keywordsEn: ["aligners", "braces"],
    keywordsFr: ["aligneurs", "bagues"],
  },
  {
    displayOrder: 76,
    slug: "orthodontics-duration",
    category: "orthodontics",
    questionAr: "كم مدة علاج التقويم؟",
    questionEn: "How long does orthodontic treatment take?",
    questionFr: "Quelle durée pour un traitement orthodontique ?",
    answerAr: "تختلف المدة حسب شدة الحالة ونوع الجهاز واستجابة الأسنان والالتزام بالمواعيد والتعليمات. يحدد الطبيب مدة تقريبية بعد التقييم.",
    answerEn: "Duration varies with severity, appliance type, tooth response, and adherence to visits and instructions. The dentist gives an approximate timeline after assessment.",
    answerFr: "Elle varie selon la sévérité, le type d’appareil, la réponse des dents et le respect des rendez-vous. Une estimation est donnée après bilan.",
    keywordsAr: ["مدة تقويم"],
    keywordsEn: ["ortho duration"],
    keywordsFr: ["durée orthodontie"],
  },
  {
    displayOrder: 77,
    slug: "orthodontics-pain",
    category: "orthodontics",
    questionAr: "هل تقويم الأسنان مؤلم؟",
    questionEn: "Is orthodontic treatment painful?",
    questionFr: "L’orthodontie est-elle douloureuse ?",
    answerAr: "قد يحدث ضغط أو انزعاج مؤقت بعد تركيب الجهاز أو تعديله، وغالبًا يتحسن خلال أيام.",
    answerEn: "Temporary pressure or discomfort can occur after placement or adjustments and usually improves within a few days.",
    answerFr: "Une pression ou un inconfort temporaire peut survenir après pose ou réglage, et s’atténue souvent en quelques jours.",
    keywordsAr: ["ألم تقويم"],
    keywordsEn: ["ortho pain"],
    keywordsFr: ["douleur ortho"],
  },
  {
    displayOrder: 78,
    slug: "cleaning-with-braces",
    category: "orthodontics",
    questionAr: "كيف أنظف أسناني أثناء التقويم؟",
    questionEn: "How do I clean my teeth with braces?",
    questionFr: "Comment se brosser avec un appareil ?",
    answerAr: "يجب استخدام فرشاة مناسبة والتنظيف حول الحاصرات والأسلاك واستخدام وسائل تنظيف إضافية حسب تعليمات الطبيب.",
    answerEn: "Use a suitable brush, clean around brackets and wires, and use additional cleaning aids as advised by the dentist.",
    answerFr: "Utilisez une brosse adaptée, nettoyez autour des bagues et fils, et suivez les aides complémentaires conseillées par le dentiste.",
    keywordsAr: ["تنظيف تقويم"],
    keywordsEn: ["braces hygiene"],
    keywordsFr: ["hygiène appareil"],
  },
  {
    displayOrder: 79,
    slug: "first-child-visit",
    category: "pediatric-dentistry",
    questionAr: "متى تكون أول زيارة للطفل إلى طبيب الأسنان؟",
    questionEn: "When should a child first visit the dentist?",
    questionFr: "Quand la première visite enfant ?",
    answerAr: "يفضل أن تبدأ الزيارات مبكرًا بعد ظهور الأسنان الأولى أو عند وجود أي مشكلة، حتى يعتاد الطفل على الفحص وتتم متابعة نمو الأسنان.",
    answerEn: "Visits preferably start early after the first teeth appear or when any issue arises, so the child becomes familiar with exams and tooth development can be monitored.",
    answerFr: "De préférence tôt après l’apparition des premières dents ou dès un problème, pour habituer l’enfant et suivre la croissance dentaire.",
    keywordsAr: ["أطفال", "زيارة"],
    keywordsEn: ["child visit"],
    keywordsFr: ["enfant visite"],
  },
  {
    displayOrder: 80,
    slug: "prepare-child-visit",
    category: "pediatric-dentistry",
    questionAr: "كيف أجهز طفلي لزيارة طبيب الأسنان؟",
    questionEn: "How do I prepare my child for a dental visit?",
    questionFr: "Comment préparer mon enfant ?",
    answerAr: "استخدم كلمات بسيطة وإيجابية، وتجنب تخويفه أو وصف العلاج بأنه مؤلم. أخبر الطبيب عن أي خوف أو تجربة سابقة.",
    answerEn: "Use simple positive words; avoid frightening them or calling treatment painful. Tell the dentist about any fear or prior experience.",
    answerFr: "Utilisez des mots simples et positifs ; évitez de faire peur ou de présenter le soin comme douloureux. Informez le dentiste de toute peur ou expérience antérieure.",
    keywordsAr: ["تجهيز طفل"],
    keywordsEn: ["prepare child"],
    keywordsFr: ["préparer enfant"],
  },
  {
    displayOrder: 81,
    slug: "baby-teeth-important",
    category: "pediatric-dentistry",
    questionAr: "هل الأسنان اللبنية مهمة؟",
    questionEn: "Are baby teeth important?",
    questionFr: "Les dents de lait sont-elles importantes ?",
    answerAr: "نعم، تساعد الأسنان اللبنية على المضغ والنطق وتحفظ المساحة للأسنان الدائمة. يجب علاج التسوس والمشكلات التي تصيبها.",
    answerEn: "Yes. Baby teeth help chewing and speech and hold space for permanent teeth. Decay and problems affecting them should be treated.",
    answerFr: "Oui. Elles aident mastication et parole et préservent l’espace pour les dents définitives. Les caries et problèmes doivent être traités.",
    keywordsAr: ["أسنان لبنية"],
    keywordsEn: ["baby teeth"],
    keywordsFr: ["dents de lait"],
  },
  {
    displayOrder: 82,
    slug: "child-broken-tooth",
    category: "pediatric-dentistry",
    questionAr: "ماذا أفعل إذا كُسر سن طفلي؟",
    questionEn: "What if my child’s tooth breaks?",
    questionFr: "Que faire si la dent de mon enfant se casse ?",
    answerAr: "تواصل مع العيادة بسرعة، واحفظ الجزء المكسور إن وجد، وتجنب العبث بالسن أو وضع مواد عليه. في حالات النزيف الشديد أو الإصابة الكبيرة اطلب رعاية عاجلة.",
    answerEn: "Contact the clinic promptly, save any broken piece if found, and avoid manipulating the tooth or placing materials on it. For severe bleeding or major injury, seek urgent care.",
    answerFr: "Contactez vite la clinique, conservez le fragment s’il y en a un, et n’y touchez pas ni n’appliquez de produits. En cas de saignement important ou traumatisme majeur, cherchez des soins urgents.",
    keywordsAr: ["كسر سن طفل"],
    keywordsEn: ["child broken tooth"],
    keywordsFr: ["dent cassée enfant"],
  },
  {
    displayOrder: 83,
    slug: "child-cavity-treatment",
    category: "pediatric-dentistry",
    questionAr: "هل يمكن علاج تسوس أسنان الأطفال؟",
    questionEn: "Can children’s tooth decay be treated?",
    questionFr: "Peut-on traiter les caries des enfants ?",
    answerAr: "نعم، يحدد الطبيب العلاج المناسب حسب عمق التسوس وعمر الطفل وحالة السن، وقد يشمل الوقاية أو الحشوة أو علاجات أخرى.",
    answerEn: "Yes. The dentist chooses care based on decay depth, the child’s age, and tooth condition; it may include prevention, fillings, or other treatments.",
    answerFr: "Oui. Le dentiste choisit selon la profondeur, l’âge et l’état de la dent : prévention, obturation ou autres soins.",
    keywordsAr: ["تسوس أطفال"],
    keywordsEn: ["child cavity"],
    keywordsFr: ["carie enfant"],
  },
  {
    displayOrder: 84,
    slug: "dental-emergencies",
    category: "dental-emergency",
    isFeatured: true,
    questionAr: "ما الحالات التي تعتبر طارئة في طب الأسنان؟",
    questionEn: "What counts as a dental emergency?",
    questionFr: "Quelles situations sont des urgences dentaires ?",
    answerAr: "تشمل الطوارئ الألم الشديد، والتورم السريع، والنزيف غير المتوقف، وإصابة الأسنان، وخروج السن من مكانه، وصعوبة التنفس أو البلع المرتبطة بتورم الفم أو الوجه.",
    answerEn: "Emergencies include severe pain, rapid swelling, uncontrolled bleeding, dental trauma, a tooth knocked out, and breathing or swallowing difficulty related to mouth or face swelling.",
    answerFr: "Douleur intense, gonflement rapide, saignement non contrôlé, traumatisme, dent expulsée, et difficulté à respirer ou avaler liée à un gonflement oral ou facial.",
    keywordsAr: ["طوارئ"],
    keywordsEn: ["emergency"],
    keywordsFr: ["urgence"],
  },
  {
    displayOrder: 85,
    slug: "severe-toothache",
    category: "dental-emergency",
    questionAr: "ماذا أفعل عند ألم أسنان شديد؟",
    questionEn: "What should I do for severe toothache?",
    questionFr: "Que faire en cas de mal de dents intense ?",
    answerAr: "تواصل مع العيادة لتقييم الحالة، وتجنب وضع الأسبرين أو مواد كيميائية على اللثة أو السن. لا تتناول أدوية لا تناسب حالتك الصحية.",
    answerEn: "Contact the clinic for assessment. Avoid placing aspirin or chemicals on gum or tooth. Do not take medication that is unsuitable for your health.",
    answerFr: "Contactez la clinique. N’appliquez pas d’aspirine ou de produits chimiques sur la gencive ou la dent. Ne prenez pas de médicaments inadaptés à votre santé.",
    keywordsAr: ["ألم شديد"],
    keywordsEn: ["toothache"],
    keywordsFr: ["mal de dents"],
  },
  {
    displayOrder: 86,
    slug: "knocked-out-tooth",
    category: "dental-emergency",
    questionAr: "ماذا أفعل إذا خرج سن دائم بسبب إصابة؟",
    questionEn: "What if a permanent tooth is knocked out?",
    questionFr: "Que faire si une dent définitive est expulsée ?",
    answerAr: "أمسك السن من التاج وليس من الجذر، ولا تفركه، وحاول حفظه في وسط مناسب مثل الحليب إن تعذر إعادته، واطلب رعاية عاجلة فورًا.",
    answerEn: "Hold the tooth by the crown (not the root), do not scrub it, try to keep it in a suitable medium such as milk if reinsertion is not possible, and seek urgent care immediately.",
    answerFr: "Tenez-la par la couronne (pas la racine), ne la frottez pas, conservez-la dans un milieu adapté comme du lait si la remise en place est impossible, et cherchez des soins immédiats.",
    keywordsAr: ["سن مخلوع"],
    keywordsEn: ["knocked out"],
    keywordsFr: ["dent expulsée"],
  },
  {
    displayOrder: 87,
    slug: "facial-swelling",
    category: "dental-emergency",
    questionAr: "ماذا أفعل عند تورم الوجه؟",
    questionEn: "What should I do for facial swelling?",
    questionFr: "Que faire en cas de gonflement du visage ?",
    answerAr: "يحتاج تورم الوجه إلى تقييم سريع، خاصة عند وجود حرارة أو صعوبة في التنفس أو البلع. في الحالات الشديدة اطلب الرعاية العاجلة فورًا.",
    answerEn: "Facial swelling needs prompt assessment, especially with fever or difficulty breathing or swallowing. In severe cases seek urgent care immediately.",
    answerFr: "Un gonflement facial nécessite une évaluation rapide, surtout avec fièvre ou difficulté à respirer ou avaler. En cas sévère, soins urgents immédiats.",
    keywordsAr: ["تورم وجه"],
    keywordsEn: ["facial swelling"],
    keywordsFr: ["gonflement visage"],
  },
  {
    displayOrder: 88,
    slug: "abscess-antibiotics-only",
    category: "dental-emergency",
    questionAr: "هل يمكن علاج خراج الأسنان بالمضاد الحيوي فقط؟",
    questionEn: "Can a dental abscess be treated with antibiotics alone?",
    questionFr: "Un abcès se traite-t-il seulement par antibiotiques ?",
    answerAr: "قد تحتاج بعض الحالات إلى مضاد حيوي، لكن علاج سبب العدوى قد يتطلب علاج العصب أو التصريف أو الخلع. لا تستخدم مضادًا حيويًا دون وصفة طبية.",
    answerEn: "Some cases may need antibiotics, but treating the infection source may require root canal therapy, drainage, or extraction. Do not use antibiotics without a prescription.",
    answerFr: "Certains cas nécessitent des antibiotiques, mais la cause peut exiger un canal, un drainage ou une extraction. N’utilisez pas d’antibiotiques sans prescription.",
    keywordsAr: ["خراج", "مضاد"],
    keywordsEn: ["abscess", "antibiotic"],
    keywordsFr: ["abcès", "antibiotique"],
  },
  {
    displayOrder: 89,
    slug: "medical-data-privacy",
    category: "privacy",
    questionAr: "هل معلوماتي الطبية محفوظة؟",
    questionEn: "Is my medical information protected?",
    questionFr: "Mes informations médicales sont-elles protégées ?",
    answerAr: "يتم التعامل مع بيانات المرضى وفق صلاحيات الوصول وسياسات الخصوصية المعتمدة في النظام، ولا تعرض المعلومات الطبية الخاصة في الصفحات العامة.",
    answerEn: "Patient data is handled according to access permissions and privacy policies in the system. Private medical information is not shown on public pages.",
    answerFr: "Les données patients sont traitées selon droits d’accès et politiques de confidentialité. Les informations médicales privées n’apparaissent pas sur les pages publiques.",
    keywordsAr: ["خصوصية", "بيانات"],
    keywordsEn: ["privacy", "data"],
    keywordsFr: ["confidentialité", "données"],
  },
  {
    displayOrder: 90,
    slug: "reviews-show-my-data",
    category: "privacy",
    questionAr: "هل تظهر بياناتي في تجارب المرضى؟",
    questionEn: "Will my details appear in patient experiences?",
    questionFr: "Mes données apparaissent-elles dans les avis ?",
    answerAr: "لا تنشر تجربة أو صورة مريض علنًا إلا بعد الموافقة المطلوبة. يمكن نشر التجربة باسم مجهول عند اختيار ذلك.",
    answerEn: "A patient story or photo is published publicly only after required consent. Stories may appear anonymously when that option is chosen.",
    answerFr: "Une expérience ou photo n’est publiée qu’avec le consentement requis. La publication peut être anonyme si choisi.",
    keywordsAr: ["تجارب", "خصوصية"],
    keywordsEn: ["reviews privacy"],
    keywordsFr: ["avis confidentialité"],
  },
  {
    displayOrder: 91,
    slug: "inquiry-form-private",
    category: "privacy",
    questionAr: "هل بيانات نموذج الاستفسار عامة؟",
    questionEn: "Is contact form data public?",
    questionFr: "Les données du formulaire sont-elles publiques ?",
    answerAr: "لا. يتم حفظ الاستفسار في النظام ليطلع عليه الموظفون المخولون فقط، ولا يعرض ضمن الموقع العام.",
    answerEn: "No. Inquiries are stored for authorized staff only and are not shown on the public website.",
    answerFr: "Non. La demande est enregistrée pour le personnel autorisé uniquement et n’apparaît pas sur le site public.",
    keywordsAr: ["استفسار", "خصوصية"],
    keywordsEn: ["inquiry privacy"],
    keywordsFr: ["demande confidentialité"],
  },
  {
    displayOrder: 92,
    slug: "are-reviews-real",
    category: "patient-experiences",
    questionAr: "هل تجارب المرضى حقيقية؟",
    questionEn: "Are patient experiences real?",
    questionFr: "Les expériences patients sont-elles authentiques ?",
    answerAr: "يعرض الموقع فقط التجارب التي تمت مراجعتها واعتمادها للنشر وفق إعدادات العيادة وموافقة النشر المطلوبة.",
    answerEn: "The website shows only experiences reviewed and approved for publication according to clinic settings and required consent.",
    answerFr: "Le site n’affiche que les expériences revues et approuvées pour publication selon les réglages et le consentement requis.",
    keywordsAr: ["تجارب حقيقية"],
    keywordsEn: ["real reviews"],
    keywordsFr: ["avis authentiques"],
  },
  {
    displayOrder: 93,
    slug: "submit-my-experience",
    category: "patient-experiences",
    questionAr: "كيف يمكنني إرسال تجربتي؟",
    questionEn: "How can I submit my experience?",
    questionFr: "Comment envoyer mon expérience ?",
    answerAr: "يمكن لفريق العيادة إضافة التجربة بعد موافقة المريض، مع إمكانية عرضها دون الاسم الحقيقي.",
    answerEn: "The clinic team can add an experience after patient consent, and it may be shown without the real name.",
    answerFr: "L’équipe peut l’ajouter après consentement du patient, éventuellement sans le nom réel.",
    keywordsAr: ["إرسال تجربة"],
    keywordsEn: ["submit review"],
    keywordsFr: ["envoyer avis"],
  },
  {
    displayOrder: 94,
    slug: "remove-my-experience",
    category: "patient-experiences",
    questionAr: "هل يمكن حذف تجربتي بعد نشرها؟",
    questionEn: "Can my experience be removed after publication?",
    questionFr: "Puis-je faire retirer mon expérience ?",
    answerAr: "يمكنك التواصل مع العيادة لطلب مراجعة أو إزالة تجربة مرتبطة بك، وسيتم التعامل مع الطلب وفق سياسة الخصوصية والموافقة.",
    answerEn: "Contact the clinic to request review or removal of an experience linked to you; the request is handled under privacy and consent policy.",
    answerFr: "Contactez la clinique pour demander révision ou retrait d’une expérience vous concernant ; la demande suit la politique de confidentialité et de consentement.",
    keywordsAr: ["حذف تجربة"],
    keywordsEn: ["remove review"],
    keywordsFr: ["retirer avis"],
  },
  {
    displayOrder: 95,
    slug: "before-after-not-guarantee",
    category: "before-after",
    questionAr: "هل صور قبل وبعد العلاج تضمن نفس النتيجة؟",
    questionEn: "Do before-and-after photos guarantee the same result?",
    questionFr: "Les photos avant/après garantissent-elles le même résultat ?",
    answerAr: "لا. تختلف النتائج حسب حالة كل مريض ونوع العلاج والاستجابة الفردية. الصور المعروضة توضيحية وليست ضمانًا لنتيجة مماثلة.",
    answerEn: "No. Results vary by each patient’s condition, treatment type, and individual response. Photos are illustrative and not a guarantee of a similar outcome.",
    answerFr: "Non. Les résultats varient selon chaque patient, le soin et la réponse individuelle. Les photos sont illustratives et ne garantissent pas un résultat identique.",
    keywordsAr: ["قبل وبعد", "نتيجة"],
    keywordsEn: ["before after", "guarantee"],
    keywordsFr: ["avant après", "garantie"],
  },
  {
    displayOrder: 96,
    slug: "before-after-not-misleading",
    category: "before-after",
    questionAr: "هل صور قبل وبعد العلاج معدلة؟",
    questionEn: "Are before-and-after photos edited misleadingly?",
    questionFr: "Les photos avant/après sont-elles retouchées de façon trompeuse ?",
    answerAr: "لا يجب استخدام تعديلات مضللة تغير النتيجة الطبية. يسمح فقط بالتحسينات التقنية مثل القص وتعديل الحجم والإضاءة المتوازنة عند الحاجة.",
    answerEn: "Misleading edits that change the clinical result must not be used. Only technical adjustments such as crop, resize, and balanced lighting are allowed when needed.",
    answerFr: "Les retouches trompeuses modifiant le résultat clinique ne doivent pas être utilisées. Seuls des ajustements techniques (recadrage, taille, éclairage équilibré) sont permis si besoin.",
    keywordsAr: ["تعديل صور"],
    keywordsEn: ["photo edit"],
    keywordsFr: ["retouche"],
  },
  {
    displayOrder: 97,
    slug: "before-after-consent",
    category: "before-after",
    questionAr: "هل تنشر صور المريض دون موافقته؟",
    questionEn: "Are patient photos published without consent?",
    questionFr: "Les photos sont-elles publiées sans consentement ?",
    answerAr: "لا يجب نشر صور الحالة دون موافقة واضحة واعتمادها للنشر، مع حماية هوية المريض قدر الإمكان.",
    answerEn: "Case photos must not be published without clear consent and publication approval, with patient identity protected as much as possible.",
    answerFr: "Elles ne doivent pas être publiées sans consentement clair et validation, en protégeant autant que possible l’identité du patient.",
    keywordsAr: ["موافقة صور"],
    keywordsEn: ["photo consent"],
    keywordsFr: ["consentement photo"],
  },
  {
    displayOrder: 98,
    slug: "whatsapp-contact",
    category: "support",
    isFeatured: true,
    questionAr: "هل يمكنني التواصل عبر واتساب؟",
    questionEn: "Can I contact you on WhatsApp?",
    questionFr: "Puis-je vous contacter sur WhatsApp ?",
    answerAr: "نعم، يمكنك استخدام زر واتساب الظاهر في صفحات الموقع للتواصل مع عيادة الوسام على الرقم 0663 09 82 08.",
    answerEn: "Yes. Use the WhatsApp button on site pages to reach Al Wissam Dental Clinic at 0663 09 82 08.",
    answerFr: "Oui. Utilisez le bouton WhatsApp des pages du site pour joindre la Clinique Dentaire El Wissam au 0663 09 82 08.",
    keywordsAr: ["واتساب"],
    keywordsEn: ["WhatsApp"],
    keywordsFr: ["WhatsApp"],
  },
  {
    displayOrder: 99,
    slug: "whatsapp-send-images",
    category: "support",
    questionAr: "هل يمكنني إرسال صور أو أشعة عبر واتساب؟",
    questionEn: "Can I send photos or X-rays via WhatsApp?",
    questionFr: "Puis-je envoyer photos ou radios via WhatsApp ?",
    answerAr: "تواصل أولًا مع العيادة لمعرفة الطريقة المناسبة والآمنة لإرسال الملفات. لا ترسل معلومات حساسة إلى أرقام غير رسمية.",
    answerEn: "Contact the clinic first for the appropriate and safe way to send files. Do not send sensitive information to unofficial numbers.",
    answerFr: "Contactez d’abord la clinique pour la méthode adaptée et sûre. N’envoyez pas d’informations sensibles à des numéros non officiels.",
    keywordsAr: ["واتساب أشعة"],
    keywordsEn: ["WhatsApp X-ray"],
    keywordsFr: ["WhatsApp radio"],
  },
  {
    displayOrder: 100,
    slug: "no-answer-found",
    category: "support",
    questionAr: "ماذا أفعل إذا لم أجد إجابة عن سؤالي؟",
    questionEn: "What if I cannot find an answer to my question?",
    questionFr: "Que faire si je ne trouve pas de réponse ?",
    answerAr: "يمكنك إرسال استفسار من صفحة التواصل، أو الاتصال بالعيادة، أو التواصل عبر واتساب للحصول على المساعدة.",
    answerEn: "You can send an inquiry from the contact page, call the clinic, or reach us on WhatsApp for help.",
    answerFr: "Envoyez une demande via Contact, appelez la clinique, ou joignez-nous sur WhatsApp.",
    keywordsAr: ["مساعدة", "دعم"],
    keywordsEn: ["help", "support"],
    keywordsFr: ["aide", "assistance"],
  },
];

export function featuredFaqSlugs(): string[] {
  return [...FEATURED_FAQ_SLUGS];
}

